# ============================================================
# reporting/email_report.py — Sends an HTML email with the dashboard
# ============================================================
# Level 3 skill covered: Pipeline Automation (scheduled reports).
# Embeds the dashboard image directly in the email body so
# the recipient doesn't need to open an attachment.

import smtplib                          # built-in Python email sending library
import base64                           # for embedding images as base64 strings
import os
import sys
from email.mime.multipart import MIMEMultipart  # lets us build HTML emails
from email.mime.text      import MIMEText       # text/HTML parts of an email

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config


def send_report(rfm):
    """
    Builds an HTML email with:
      - A segment summary table
      - The dashboard image embedded inline (no attachment needed)
    Sends it via Gmail SMTP using the settings in config.py.
    Skips silently if EMAIL_PASS is not set in config.py.
    """

    # ── Skip if email is not configured ──────────────────────────────────────
    if not config.EMAIL_PASS:
        print("Email not configured (EMAIL_PASS is empty in config.py) — skipping.")
        return

    print("--- Sending email report ---")

    # ── Build the segment summary HTML table ─────────────────────────────────
    summary = (rfm.groupby("Segment")
               .agg(Customers=("Customer ID", "count"),
                    Revenue=("Monetary", "sum"))
               .sort_values("Revenue", ascending=False))

    # Build an HTML <table> row by row using a regular Python loop
    table_rows = ""
    for segment, row in summary.iterrows():
        table_rows += (f"<tr><td>{segment}</td>"
                       f"<td>{int(row['Customers'])}</td>"
                       f"<td>£{row['Revenue']:,.0f}</td></tr>\n")

    # ── Embed the dashboard image as base64 ──────────────────────────────────
    # base64 encoding converts a binary image file into a plain text string.
    # This lets us paste the image directly inside the HTML — no attachment needed.
    # "rb" mode = open the file in binary (read) mode — required for images and non-text files.
    # base64.b64encode() converts the raw bytes into base64 bytes.
    # .decode("utf-8") converts those base64 bytes into a regular Python string we can embed in HTML.
    img_path = os.path.join(config.OUTPUT_FOLDER, config.DASHBOARD_IMG)
    with open(img_path, "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode("utf-8")

    # ── Build the full HTML email body ────────────────────────────────────────
    # f"""...""" is a multi-line f-string — triple quotes let us write across many lines
    # without needing \n escape characters.
    # The f prefix means Python will replace {variables} with their actual values.
    # {table_rows} will be replaced with the HTML table rows we built above.
    html_body = f"""
    <html><body>
    <h2>📊 Weekly LTV Report</h2>
    <p>Here is the latest customer segment breakdown:</p>
    <table border="1" cellpadding="6" style="border-collapse:collapse;">
      <tr><th>Segment</th><th>Customers</th><th>Revenue</th></tr>
      {table_rows}
    </table>
    <br>
    <img src="data:image/png;base64,{img_b64}" width="700" alt="LTV Dashboard"/>
    <p><small>Generated by twp-python-cookbook LTV Engine</small></p>
    </body></html>
    """

    # ── Assemble the email message ────────────────────────────────────────────
    # MIMEMultipart("alternative") creates an email that can contain multiple versions
    # of the same content (e.g. a plain-text version AND an HTML version).
    # Email clients will automatically display the HTML version if they support it,
    # or fall back to plain text on older clients.
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Weekly Customer LTV Report"
    msg["From"]    = config.EMAIL_FROM
    msg["To"]      = ", ".join(config.EMAIL_TO)
    msg.attach(MIMEText(html_body, "html"))

    # ── Connect to Gmail and send ─────────────────────────────────────────────
    # smtplib.SMTP() opens a connection to the email server.
    # starttls() upgrades the connection to an encrypted (TLS) channel.
    # login() authenticates with our Gmail App Password.
    with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
        server.starttls()
        server.login(config.EMAIL_FROM, config.EMAIL_PASS)
        server.sendmail(config.EMAIL_FROM, config.EMAIL_TO, msg.as_string())

    print(f"Email sent to: {config.EMAIL_TO}\n")
